Controllers/ArticleController.cs
using GitBlog.Data;
using GitBlog.Models;
using GitBlog.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace GitBlog.Controllers
{
    public class ArticleController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ArticleController(AppDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            if (User.IsInRole(WC.AdminRole) != true)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                IEnumerable<Article> objList = _db.Articles.Include(u => u.Category);
                return View(objList);
            }
        }
        //Get upsert
        public IActionResult Upsert(int? id)
        {
            ArticleVM articleVM = new ArticleVM()
            {
                Article = new Article(),
                CategorySelectList = _db.Category.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
            };

            if (id == null)
            {
                //this is for create
                return View(articleVM);
            }
            else
            {
                articleVM.Article = _db.Articles.Find(id);
                if (articleVM.Article == null)
                {
                    return NotFound();
                }
                return View(articleVM);
            }
        }

        //Post upsert
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ArticleVM articleVM)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                string webRootPath = _webHostEnvironment.WebRootPath;
                if (articleVM.Article.Id == 0)
                {
                    //Create
                    string upload = webRootPath + WC.ArticlesImagePath;
                    string filename = Guid.NewGuid().ToString();
                    string extension = Path.GetExtension(files[0].FileName);

                        using (var filestram = new FileStream(Path.Combine(upload, filename + extension), FileMode.Create))
                        {
                            files[0].CopyTo(filestram);
                        }

                        articleVM.Article.Image = filename + extension;

                        _db.Articles.Add(articleVM.Article);
                   
                }
                else
                {
                    //Update
                    var ObjFromDb = _db.Articles.AsNoTracking().FirstOrDefault(u => u.Id == articleVM.Article.Id);

                    if (files.Count > 0)
                    {
                        string upload = webRootPath + WC.ArticlesImagePath;
                        string filename = Guid.NewGuid().ToString();
                        string extension = Path.GetExtension(files[0].FileName);

                        var oldFile = Path.Combine(upload, ObjFromDb.Image);

                        if (System.IO.File.Exists(oldFile))
                        {
                            System.IO.File.Delete(oldFile);
                        }

                        using (var filestram = new FileStream(Path.Combine(upload, filename + extension), FileMode.Create))
                        {
                            files[0].CopyTo(filestram);
                        }

                        articleVM.Article.Image = filename + extension;
                    }
                    else
                    {
                        articleVM.Article.Image = ObjFromDb.Image;
                    }
                    _db.Articles.Update(articleVM.Article);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            articleVM.CategorySelectList = _db.Category.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            });
            return View(articleVM);
        }

        //Get delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Article article = _db.Articles.Include(u => u.Category).FirstOrDefault(u => u.Id == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        //Post delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Articles.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            string upload = _webHostEnvironment.WebRootPath + WC.ArticlesImagePath;
            var oldFile = Path.Combine(upload, obj.Image);

            if (System.IO.File.Exists(oldFile))
            {
                System.IO.File.Delete(oldFile);
            }

            _db.Articles.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

Controllers/CategoryController.cs
using GitBlog.Data;
using GitBlog.Models;
using GitBlog.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GitBlog.Controllers
{
    public class CategoryController : Controller
    {

        private readonly AppDbContext _db;

        public CategoryController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            if (User.IsInRole(WC.AdminRole) != true)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                IEnumerable<Category> objList = _db.Category;
                return View(objList);
            }
           
        }


        //Get upsert
        public IActionResult Upsert(int? id)
        {
            CategoryVM categoryVM = new CategoryVM()
            {
                Category = new Category(),
            };

            if (id == null)
            {
                //this is for create
                return View(categoryVM);
            }
            else
            {
                categoryVM.Category = _db.Category.Find(id);
                if (categoryVM.Category == null)
                {
                    return NotFound();
                }
                return View(categoryVM);
            }
        }

        //Post upsert
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(CategoryVM categoryVM)
        {
            if (ModelState.IsValid)
            {
                if (categoryVM.Category.Id == 0)
                {
                    //Create
                    _db.Category.Add(categoryVM.Category);
                }
                else
                {
                    //Update
                    var ObjFromDb = _db.Category.AsNoTracking().FirstOrDefault(u => u.Id == categoryVM.Category.Id);
                    _db.Category.Update(categoryVM.Category);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categoryVM);
        }
        
        //Get delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Category category = _db.Category.FirstOrDefault(u => u.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        //Post delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Category.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Category.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

Views/Shared/_ArticleWindow.cshtml
@model GitBlog.Models.Article

<div class=" m-2 col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(' ', '_')">
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row text-center">
            <div class="col-8 border-dark p-1"> <h6> @Model.Name </h6> </div>
            <div class="col-4">
                <span class="badge p-2 border w-100 bg-dark text-light">@Model.Category.Name</span>
            </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@WC.ArticlesImagePath@Model.Image" alt="Card image cap">
        <div class="card-body p-1 px-3 row">
            <div class="col-12 pt-2 text-center" style="font-size:13px; text-align:justify">
                <p> @Model.ShortDesccription</p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GitBlog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
               
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GitBlog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(WC.AdminRole) == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Article" asp-action="Index">Articles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Register">Register admin</a>
                            </li>

                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GitBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>